name: webpack CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: yarn install dependencies
      run: yarn
    - name: yarn build using webpack
      run: yarn build
    - name: delete main.js
      run: rm dist/main.js
    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: dist/

      
