name: webpack CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: yarn install dependencies
      run: yarn
    - name: yarn build using webpack
      run: yarn build
    - name: delete main.js
      run: rm dist/main.js
    - name: GitHub Pages Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.GH_PAT }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: dist
        BUILD_SCRIPT: rm dist/main.js

      
